const IPC_MESSAGES = {
    SHOW_WELCOME_MESSAGE: 'SHOW_WELCOME_MESSAGE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_PROFILE: 'GET_PROFILE',
    SET_PROFILE: 'SET_PROFILE',
    START_MONITORING: 'START_MONITORING',
    STOP_MONITORING: 'STOP_MONITORING',
    REGISTER: 'REGISTER',
}

module.exports = {
    IPC_MESSAGES: IPC_MESSAGES,
}